spring.application.name=digital-banking
# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# DATABASE CONFIG
# ===============================
spring.datasource.url=jdbc:postgresql://ep-crimson-poetry-ai4o5ihx-pooler.c-4.us-east-1.aws.neon.tech/digital_banking_db?user=neondb_owner&password=npg_CIZb29gSjtDu&sslmode=require&channelBinding=require
#spring.datasource.username=postgres
#spring.datasource.password=demo123
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
